services:
  gateway:
    build:
      context: ./services/gateway
    container_name: gateway
    environment:
      STORAGE_SERVICES: http://storage1:8000,http://storage2:8000,http://storage3:8000
      REQUEST_TIMEOUT: "1.5"
      HEALTH_CHECK_INTERVAL: "3"
    ports:
      - "8080:8080"

  storage1:
    build:
      context: ./services/storage
    container_name: storage1
    environment:
      SERVICE_NAME: storage1
    ports:
      - "8001:8000"

  storage2:
    build:
      context: ./services/storage
    container_name: storage2
    environment:
      SERVICE_NAME: storage2
    ports:
      - "8002:8000"

  storage3:
    build:
      context: ./services/storage
    container_name: storage3
    environment:
      SERVICE_NAME: storage3
    ports:
      - "8003:8000"
