services:
  gateway:
    build:
      context: ./services/gateway
    ports:
      - "8080:8000"
    env_file:
      - ./services/gateway/.env.gateway
    networks:
      app_net:
        ipv4_address: 172.31.0.10

  storage-1:
    build:
      context: ./services/storage
    ports:
      - "8081:8000"
    env_file:
      - ./services/storage/.env.storage-1
    networks:
      app_net:
        ipv4_address: 172.31.0.11

  storage-2:
    build:
      context: ./services/storage
    ports:
      - "8082:8000"
    env_file:
      - ./services/storage/.env.storage-2
    networks:
      app_net:
        ipv4_address: 172.31.0.12

  storage-3:
    build:
      context: ./services/storage
    ports:
      - "8083:8000"
    env_file:
      - ./services/storage/.env.storage-3
    networks:
      app_net:
        ipv4_address: 172.31.0.13

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
